apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-performance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-performance
  template:
    metadata:
      labels:
        app: student-performance
    spec:
      containers:
        - name: student-performance
          image: xenolinhhv/student-performance-prediction:e8975267cf292347f2e38c44356ce1e2a586f68f
          ports:
            - containerPort: 8000