apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: student-performance

spec:
  replicas: 1

  selector:
    matchLabels:
      app: student-performance

  template:
    metadata:
      labels:
        app: student-performance

    spec:
      containers:
        - name: student-performance
          image: xenolinhhv/student-performance-prediction:YOUR_IMAGE_TAG
          ports:
            - containerPort: 8000

  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 100