apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-performance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-performance
  template:
    metadata:
      labels:
        app: student-performance
    spec:
      containers:
        - name: student-performance
          image: xenolinhhv/student-performance-prediction:2091201846a1d84418c585be91de0f3dbcd98f2f1
          ports:
            - containerPort: 8000