apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: student-performance

spec:
  replicas: 1

  selector:
    matchLabels:
      app: student-performance

  template:
    metadata:
      labels:
        app: student-performance

    spec:
      containers:
        - name: student-performance
          image: xenolinhhv/student-performance-prediction:ee50b9d15e0f9700ad937550729c3155b76c1389
          ports:
            - containerPort: 8000

  strategy:
    canary:
      stableService: student-performance-service
      canaryService: student-performance-canary

      steps:
        - setWeight: 20

        - analysis:
            templates:
              - templateName: student-performance-health-check

        - setWeight: 50

        - analysis:
            templates:
              - templateName: student-performance-health-check

        - setWeight: 100