apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: student-performance

spec:
  replicas: 1

  selector:
    matchLabels:
      app: student-performance

  template:
    metadata:
      labels:
        app: student-performance

    spec:
      containers:
        - name: student-performance
          image: xenolinhhv/student-performance-prediction:86cc49f8fe7ac1cd7bba2e52f73d093f7d9b1ba5
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: student-performance-secret
                  key: SECRET_KEY

  strategy:
    canary:
      stableService: student-performance-service
      canaryService: student-performance-canary

      steps:
        - setWeight: 20

        - analysis:
            templates:
              - templateName: student-performance-health-check

        - setWeight: 50

        - analysis:
            templates:
              - templateName: student-performance-health-check

        - setWeight: 100